# Generated by Django 5.2.6 on 2025-11-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_hall',
            field=models.ForeignKey(blank=True, help_text='Currently assigned hall', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to='api.hall'),
        ),
        migrations.AddField(
            model_name='event',
            name='hall_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When hall was last assigned', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_hall',
            field=models.ForeignKey(blank=True, help_text='Preferred hall for the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_events', to='api.hall'),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_hall',
            field=models.ForeignKey(blank=True, help_text='Backup hall for the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_events', to='api.hall'),
        ),
    ]
