# Generated by Django 5.2.6 on 2025-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
