# Generated by Django 5.2.6 on 2025-11-21 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/club_organizers/')),
                ('designation_in_club', models.CharField(blank=True, help_text='e.g., President, Secretary, Treasurer, Coordinator', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
