# Generated by Django 5.2.6 on 2025-11-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cluborganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluborganizer',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizers', to='api.club'),
        ),
    ]
