# Generated by Django 5.2.6 on 2025-11-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usernotificationpreferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature for certificate signing (JPEG/PNG)', null=True, upload_to='signatures/mentors/'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Digital signature for certificate signing (JPEG/PNG)', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('club_organizer', 'Club Organizer'), ('admin', 'Admin'), ('principal', 'Principal')], default='student', max_length=20),
        ),
    ]
