# Generated by Django 5.2.6 on 2025-11-28 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mentor_signature_user_signature_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(help_text="Principal's digital signature for certificates (JPEG/PNG)", upload_to='signatures/principal/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the signature upload', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Principal Signature',
                'verbose_name_plural': 'Principal Signatures',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
