# Generated by Django 5.2.6 on 2025-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_principalsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(choices=[('regular', 'Regular Student'), ('lateral', 'Lateral Entry Student')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='aictecategory',
            name='max_points_allowed',
            field=models.IntegerField(default=20, help_text='Maximum points that can be awarded (default 20 per VTU rules)'),
        ),
    ]
