# Generated by Django 5.2.6 on 2025-12-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_admission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='awardsAictePoints',
            field=models.BooleanField(default=False, help_text='Whether event awards AICTE points'),
        ),
        migrations.AddField(
            model_name='event',
            name='needsVenueCampus',
            field=models.BooleanField(default=False, help_text='Whether event requires college campus venue'),
        ),
    ]
