# Generated by Django 5.2.6 on 2025-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_awardsaictepoints_event_needsvenuecampus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aictepointtransaction',
            name='verification_code',
            field=models.CharField(blank=True, help_text='8-character verification code for mentor approval', max_length=8, null=True),
        ),
    ]
