# Generated by Django 5.2.6 on 2025-12-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aictepointtransaction_verification_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aictepointtransaction',
            unique_together={('student', 'event')},
        ),
    ]
