# Generated by Django 5.2.6 on 2025-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_aictepointtransaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('club_organizer', 'Club Organizer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
