# Generated by Django 5.1.4 on 2025-01-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='generated_file',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, default='generated_certificates/default.pdf', upload_to='generated_certificates/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], default='pdf', help_text='Type of the template (PDF or Image)', max_length=10),
        ),
    ]
