# Generated by Django 5.1.4 on 2025-01-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cert', '0002_alter_participant_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='certificate_template',
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_template', to='Cert.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='Cert.event'),
        ),
    ]
