# Generated by Django 5.1.4 on 2025-01-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cert', '0007_remove_certificate_student_remove_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='generated_file',
            field=models.BinaryField(default=b''),
        ),
    ]
